name: Status Check Function
on: push
jobs:
    fail:
        runs-on: ubuntu-latest
        steps:
            - run: echo "test01"
            - run: exit 1
            - run: echo "Hello"
              if: ${{failure()}}