name: Variable
on: push
jobs: 
   print:
    runs-on: ubuntu-latest
    env:
        USERNAME: ${{vars.USERNAME}}
        PASSWORD: ${{secrets.PASSWORD}}
    steps:
        - run: echo "${USERNAME}" 
        - run: echo "${PASSWORD}"
        - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"