name: Parallel jobs
on: push
jobs:
    before:
        runs-on: ubuntu-latest
        steps:
            - id: generate
              run: echo "answer=Hello" >> "${GITHUB_OUTPUT}"
        outputs:
            result: ${{ steps.generate.outputs.answer}}
    after:
        runs-on: ubuntu-latest
        needs: [before]
        steps:
            - env:
                RESULT: ${{ needs.before.outputs.answer }}
              run: echo "${RESULT}"
    first-1:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 10 && echo "First job"
    first-2:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 10 && echo "First job"
    second:
        runs-on: ubuntu-latest
        needs: [first-1, first-2]
        steps:
            - run: sleep 10 && echo "Second job"
    third:
        runs-on: ubuntu-latest
        needs: [second]
        steps:
            - run: sleep 10 && echo "Third job"
    print-matrix:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - run: echo "${RUNNER_OS}"
              shell: bash