name: Parallel jobs
on: push
jobs:
    first-1:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 10 && echo "First job"
    first-2:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 10 && echo "First job"
    second:
        runs-on: ubuntu-latest
        needs: [first-1, first-2]
        steps:
            - run: sleep 10 && echo "Second job"
    third:
        runs-on: ubuntu-latest
        needs: [second]
        steps:
            - run: sleep 10 && echo "Third job"