name: Test
on:
    workflow_dispatch:
    pull_request:
        paths: ['go/**/*.go']
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                token: ${{secrets.GITHUB_TOKEN}}
            - uses: actions/setup-go@v4
              with:
                go-version: '1.22'
            - run: go test go/excellent/*.go